workflows:
  ios-workflow:
    name: Build & Upload iOS App
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "th.ac.chomsurang.app"
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --build-name=3.1.0 --build-number=29
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth:
          apple_id: dorayagi@gmail.com
          api_key_id: G9A8MHP9T6
          issuer_id: 3cdd00be-36f5-4047-a99e-439c53b66d13
          api_private_key: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU4HXe5SXBy8FSIRr
            5Zzmxp6HVS/QTsBn3885qo9liXCgCgYIKoZIzj0DAQehRANCAAS3OxxKNApvvA+A
            qQwHugkLLMRl+7ijAzS+QvvsRWkHT14znH3wB95eg7MawvzJlecV6zj2lZVJHjjc
            3o5q2IGi
            -----END PRIVATE KEY-----
