workflows:
  ios-workflow:
    name: iOS Build & Upload
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store  # หรือ development หรือ ad_hoc ตามความต้องการ
        bundle_identifier: chomsurang  # แก้เป็น bundle ID ของแอปคุณ
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files $(BUNDLE_ID) --type IOS_APP_STORE --create
      - name: Build .ipa
        script: flutter build ipa --release --build-name=3.1.0 --build-number=29
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU4HXe5SXBy8FSIRr
          5Zzmxp6HVS/QTsBn3885qo9liXCgCgYIKoZIzj0DAQehRANCAAS3OxxKNApvvA+A
          qQwHugkLLMRl+7ijAzS+QvvsRWkHT14znH3wB95eg7MawvzJlecV6zj2lZVJHjjc
          3o5q2IGi
          -----END PRIVATE KEY-----
        key_id: G9A8MHP9T6
        issuer_id: 3cdd00be-36f5-4047-a99e-439c53b66d13